// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYks71_49PfIhDpe4_tREjj5tMffRFvCo',
    appId: '1:9460337592:web:533826b328a259db6b5d4d',
    messagingSenderId: '9460337592',
    projectId: 'refa-177bc',
    authDomain: 'refa-177bc.firebaseapp.com',
    storageBucket: 'refa-177bc.firebasestorage.app',
    measurementId: 'G-CXB8FDLZNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD3HDpOgDgSKj-ZBsF83GTIvTOEnJu7hg',
    appId: '1:9460337592:android:ace8d11de21fbe596b5d4d',
    messagingSenderId: '9460337592',
    projectId: 'refa-177bc',
    storageBucket: 'refa-177bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUtgf-Tk7nriGAPXf_39zuapj4Ooy4Pnw',
    appId: '1:9460337592:ios:d4fd08ba170526dc6b5d4d',
    messagingSenderId: '9460337592',
    projectId: 'refa-177bc',
    storageBucket: 'refa-177bc.firebasestorage.app',
    iosBundleId: 'com.refa.refaMobil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUtgf-Tk7nriGAPXf_39zuapj4Ooy4Pnw',
    appId: '1:9460337592:ios:d4fd08ba170526dc6b5d4d',
    messagingSenderId: '9460337592',
    projectId: 'refa-177bc',
    storageBucket: 'refa-177bc.firebasestorage.app',
    iosBundleId: 'com.refa.refaMobil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYks71_49PfIhDpe4_tREjj5tMffRFvCo',
    appId: '1:9460337592:web:730a3cc867f3502d6b5d4d',
    messagingSenderId: '9460337592',
    projectId: 'refa-177bc',
    authDomain: 'refa-177bc.firebaseapp.com',
    storageBucket: 'refa-177bc.firebasestorage.app',
    measurementId: 'G-6HP7RD18LY',
  );
}
